// <auto-generated />
using Integrator.DataAccess.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Integrator.Frontend.Migrations.Application
{
    [DbContext(typeof(IntegratorDbContext))]
    [Migration("20250330190823_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Integrator.DataAccess.Models.Complaints.Complaint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ComplaintDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ComplaintNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("CreatedAt")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UpdatedAt")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Complaints");
                });
#pragma warning restore 612, 618
        }
    }
}
