<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.13" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Serilog" Version="4.2.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
      <PackageReference Include="Serilog.Enrichers.ClientInfo" Version="2.1.2" />
      <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Integrator.Shared\Integrator.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\css\dark.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\light.css" />
      <_ContentIncludedByDefault Remove="wwwroot\img\avatars\avatar-2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\avatars\avatar-3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\avatars\avatar-4.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\avatars\avatar-5.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\avatars\avatar.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ad.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ae.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\af.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ag.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ai.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\al.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\am.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\an.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ao.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\aq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ar.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\as.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\at.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\au.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\aw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ax.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\az.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ba.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bb.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bd.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\be.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bi.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\br.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bs.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\by.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\bz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ca.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cd.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ch.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ci.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ck.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\co.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cx.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cy.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\cz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\de.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\dj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\dk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\dm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\do.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\dz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ec.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ee.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\eg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\eh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\er.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\es.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\et.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\eu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\fi.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\fj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\fk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\fm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\fo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\fr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ga.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gb-eng.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gb-nir.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gb-sct.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gb-wls.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gb.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gd.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ge.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gi.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gp.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gs.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\gy.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\hk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\hm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\hn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\hr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ht.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\hu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\id.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ie.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\il.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\im.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\in.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\io.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\iq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ir.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\is.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\it.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\je.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\jm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\jo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\jp.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ke.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\kg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\kh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ki.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\km.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\kn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\kp.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\kr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\kw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ky.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\kz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\la.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\lb.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\lc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\li.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\lk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\lr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ls.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\lt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\lu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\lv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ly.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ma.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\md.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\me.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ml.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mp.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ms.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mx.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\my.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\mz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\na.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\nc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ne.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\nf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ng.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ni.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\nl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\no.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\np.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\nr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\nu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\nz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\om.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pa.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pe.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ph.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ps.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\pw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\py.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\qa.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\re.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ro.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\rs.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ru.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\rw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sa.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sb.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sd.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\se.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\si.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\so.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ss.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\st.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sx.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sy.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\sz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\td.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\th.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\to.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\tz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ua.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ug.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\um.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\us.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\uy.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\uz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\va.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\vc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ve.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\vg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\vi.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\vn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\vu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\wf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ws.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\xk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\ye.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\yt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\za.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\zm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\flags\zw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\icons\brand-1.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\icons\brand-2.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\icons\brand-3.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\icons\brand-4.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\icons\brand-5.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\icons\icon-48x48.png" />
      <_ContentIncludedByDefault Remove="wwwroot\img\photos\unsplash-1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\photos\unsplash-2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\img\photos\unsplash-3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\bootstrap\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\bootstrap\bootstrap.min.css.map" />
    </ItemGroup>

</Project>
